### ISSUE TITLE
Define __slots__ for Entity

### ISSUE THREAD

**Issue by rcfox** [seanfisk/ecs#4]
Since there are likely to be many Entity objects, and they each only hold one value, you should define **slots** in the class to reflect this, which will prevent allocation of a dictionary for each object.

See: http://docs.python.org/2/reference/datamodel.html#slots

**Comment by seanfisk** [comment]
That's a great idea!

It actually touches on another issue I've been meaning to address: **benchmarks**. I think that it's always a good idea to back up performance optimizations with benchmarks. I already have [one optimization](https://github.com/seanfisk/ecs/blob/master/ecs/managers.py#L200) that I'd like to see a bench on. Hopefully I'll have time to add this soon.
